# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  coreai-mcu-responses:
    build:
      target: development
    image: coreai-mcu-responses-development
    container_name: coreai-mcu-responses-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
      - coreai-mcu-responses-azurite
    environment:
      MESSAGE_QUEUE_HOST: test
      MESSAGE_QUEUE_USER: test
      MESSAGE_QUEUE_PASSWORD: test
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-coreai-mcu-events}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}

  coreai-mcu-responses-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
