services:
  coreai-mcu-responses:
    build:
      context: .
      target: production
    image: coreai-mcu-responses
    container_name: coreai-mcu-responses
    depends_on:
      - coreai-mcu-responses-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-responses-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-test}
  
  coreai-mcu-responses-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
