version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  coreai-mcu-responses:
    build:
      target: development
    image: coreai-mcu-responses-development
    container_name: coreai-mcu-responses-development
    depends_on:
      - coreai-mcu-responses-azurite
    ports:
      - "${CORE_AI_RESPONSES_PORT:-3000}:3000"
      - "${CORE_AI_RESPONSES_DEBUG_PORT:-9229}:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-coreai-mcu-events}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}
  
  coreai-mcu-responses-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${CORE_AI_RESPONSES_TABLE_PORT:-10002}:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
