- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: RESPONSE_PROCESSING_QUEUE_ADDRESS
  value: "coreai-mcu-response"
- key: EVENTS_TOPIC_ADDRESS
  value: "coreai-mcu-events"
- key: AZURE_STORAGE_ACCOUNT
  value: "{{servicename}}-AZURE-STORAGE-ACCOUNT"
  type: "keyvault"
