storageAccounts:
  - name: 'coreaimcu'
    owner: 'no'
    tables: 
      - name: 'responses'
        roleAssignments:
          - roleName: 'TableDataContributor'

namespaceTopics:
  - name: events
    owner: 'no'
    roleAssignments:
      - roleName: 'TopicSender'

namespaceQueues:
  - name: response
    roleAssignments:
      - roleName: 'QueueReceiver'
