storageAccounts:
  - name: 'coreaimcu'
    owner: 'no'
    roleAssignments:
      - roleName: 'DataWriter'
    blobContainers:
      - name: 'finalisedresponses'
    tables: 
      - name: 'responses'

namespaceTopics:
  - name: events
    roleAssignments:
      - roleName: 'TopicSender'

namespaceQueues:
  - name: response
    roleAssignments:
      - roleName: 'QueueReceiver'
